Allow Mosaic to display UTF-8 encoded characters
alandipert/ncsa-mosaic pull request #18
Opened 2022-04-16 07:44 UTC by edorig

Using the Motif 2.x function XmStringDraw, with ISO 10646-1 fonts Mosaic can display UTF8 encoded characters in HTML pages. With a more complete list of HTML character entitites in HTMLamp.h this also permits to display math symbols, greek and cyrillic characters and miscellaneous symbols. 
Using XmStringCreateLocalized in the place of XmStringCreateSimple allows Mosaic to display UTF-8 characters in the URL or in a file list.
If the UTF-8 characters are not displayed correctly, one should change the default font using xrdb -merge Mosaic.ad

2022-04-16 14:41 UTC, clausecker commented
Works like a charm!

2022-04-16 14:46 UTC, clausecker requested changes
Looks good!  Some minor things must be fixed and I can merge this.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLformat.c
> +		/*		XDrawString(XtDisplay(hw),
Please remove instead of commenting out.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLformat.c
> +		/*		XDrawString(XtDisplay(hw),
Please remove instead of commenting out.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLtable.c
> +		/*
Please remove instead of commenting out.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +int ucs2utf8(unsigned int ucs,char code[4])
Please use same indentation style as remaining code.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +			fprintf(stderr,"&#%ud character: %s\n",ucs,val);
Please fix formatting (missing spaces).  Also: is this debug printout really needed all the time?  Seems like it could become very noisy.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +			fprintf(stderr,"&#%ud character: %s\n",ucs,val);
Same here.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +				fprintf(stderr,"&xxx; character:%s\n",val);
And here.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +		if (lng>0)
Please fix formatting (missing spaces).

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +		// ptr2++;
Please remove commented code.

2022-04-16 14:46 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +			}
Please fix indentation and formatting.

2022-04-16 20:41 UTC, clausecker commented
Please reopen this one instead of making a new one so I can check

2022-04-16 20:50 UTC, clausecker requested changes
Almost done now!  Please just push new commits to the PR instead of making a new PR.

2022-04-16 20:50 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +int ucs2utf8(unsigned int ucs,char code[4])
That's slightly better now, but the second level of indentation is still in GNU style, not the project's style.  All indentation should be one tab per level and no “braces at half the indentation” stuff.

2022-04-16 20:50 UTC, clausecker commented on libhtmlw/HTMLparse.c
> +			fprintf(stderr,"&#%ud character: %s\n",ucs,val);
Well the formatting is still rather weird (spaces are not rationed; I don't understand why you write statements without any spaces around the operators), but it's good enough maybe.

2022-04-17 14:05 UTC, merged

2025-09-23 11:10 UTC, 1996christianlopezux75 approved these changes